language: python

python: '3.8'

cache: pip

install:
  - pip3 install -r requirements.txt

stages:
  - test
  - lint

jobs:
  include:
    - stage: test
      script:
        - . ./config/run-tests.sh
    - stage: lint
      script:
        - pylint ./**/*.py

notifications:
  email: true