language: python

python: '3.8'

os: linux

dist: xenial

cache: pip

install:
  - pip3 install -r requirements.txt

stages:
  - test
  - lint
  - plagiarism_check

jobs:
  include:
    - stage: test
      script:
        - bash config/run-tests.sh
    - stage: lint
      script:
        - pylint ./**/*.py
    - stage: plagiarism_check
      script:
        - if [ -n "$TRAVIS_COMMIT" ]; then echo yes to commit; fi
        - if [ -n "$FIPL_ACCESS_TOKEN" ]; then echo yes to token; fi
        - python3 config/pr_crawler.py
        - bash config/run-plagiarism-check.sh

notifications:
  email:
    on_success: always
    on_failure: always
