language: python

python: '3.8'

os: linux

dist: xenial

cache: pip

install:
  - pip3 install -r requirements.txt

stages:
  - test
  - lint

jobs:
  include:
    - stage: test
      script:
        - bash config/run-tests.sh
    - stage: lint
      script:
        - LINT_OUTPUT=$(pylint ./**/*.py)
        - echo $LINT_OUTPUT
        - SCORE=$(echo $LINT_OUTPUT | grep -oP "Your code has been rated at \d+.\d+" | grep -oP "\d+")
        - echo $SCORE
        - NUMBER=$(echo $SCORE | awk '{ print $1 }')
        - echo $NUMBER
        - if $NUMBER < 6; then exit 1
        - if $NUMBER >= 6; then exit 0

notifications:
  email:
    on_success: always
    on_failure: always
